'use client';

import { useState } from 'react';
import Navbar from '@/components/Navbar';

export default function InstantCodePage() {
  const [prompt, setPrompt] = useState('');
  const [selectedTemplate, setSelectedTemplate] = useState('web');
  const [generatedCode, setGeneratedCode] = useState('');

  const templates = [
    {
      id: 'web',
      title: 'Website',
      description: 'Landing page, blog, atau portfolio',
      icon: (
        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
        </svg>
      )
    },
    {
      id: 'api',
      title: 'REST API',
      description: 'Backend service dan endpoint',
      icon: (
        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
      )
    },
    {
      id: 'mobile',
      title: 'Mobile App',
      description: 'Android dan iOS app',
      icon: (
        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z" />
        </svg>
      )
    },
    {
      id: 'automation',
      title: 'Automation',
      description: 'Script dan workflow otomatis',
      icon: (
        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
        </svg>
      )
    }
  ];

  const handleGenerateCode = () => {
    // Simulasi generate code dengan gaya programmer malas 😴
    const demoCode = `// 🦥 Generated ${selectedTemplate.toUpperCase()} Code
    // 💭 Based on your request: ${prompt}
    // 🎯 Generated by AI karena males ngoding sendiri
    
    /* Tips dari programmer malas:
     * - Copy paste adalah seni
     * - Stack Overflow adalah sahabat
     * - Kalau bisa diautomasi, kenapa harus manual?
     */
    
    // Contoh kode template ${selectedTemplate}
    function lazyDemo() {
      // TODO: Implement something keren disini
      // Tapi nanti aja, sekarang ngopi dulu ☕
    
      if (needsMoreFeatures) {
        console.log("Besok aja tambahnya...");
        return "🚧 Work in Progress";
      }
    
      // Fungsi yang sebenarnya
      return "✨ Magic happens here!";
    }
    
    // Pro tip: Jangan lupa istirahat
    // Coding bisa besok, tidur siang tidak bisa ditunda 😴
    `;
    
    setGeneratedCode(demoCode);
  };

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-foreground mb-4">
            Generator Kode Instan
          </h1>
          <p className="text-lg text-foreground/70 max-w-2xl mx-auto">
            Buat kode program tanpa perlu ngoding. Cukup pilih template dan kasih tau apa yang kamu mau!
          </p>
        </div>

        {/* Template Selection */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          {templates.map((template) => (
            <button
              key={template.id}
              onClick={() => setSelectedTemplate(template.id)}
              className={`p-4 rounded-xl border transition-colors text-left flex items-start gap-4 ${selectedTemplate === template.id ? 'bg-foreground text-background' : 'border-foreground/10 hover:border-foreground/20'}`}
            >
              <div className={`${selectedTemplate === template.id ? 'text-background' : 'text-foreground/70'}`}>
                {template.icon}
              </div>
              <div>
                <h3 className="font-semibold">{template.title}</h3>
                <p className={`text-sm ${selectedTemplate === template.id ? 'text-background/70' : 'text-foreground/70'}`}>
                  {template.description}
                </p>
              </div>
            </button>
          ))}
        </div>

        {/* Prompt Input */}
        <div className="mb-8">
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Malas ngoding? Sama! 🤪 Cukup jelasin aja mau bikin apa... (contoh: landing page toko kue yang keren banget tapi males bikinnya 😴)" 
            className="w-full h-32 p-4 rounded-xl bg-black/90 text-white border border-foreground/10 focus:border-foreground/20 focus:ring-0 resize-none placeholder:text-gray-500"
          />
          <p className="text-sm text-foreground/50 mt-2 italic">Santai aja, biar AI yang ngoding buat kamu 🦥</p>
          <button
            onClick={handleGenerateCode}
            disabled={!prompt.trim()}
            className="w-full mt-4 bg-foreground text-background py-3 rounded-lg hover:bg-foreground/90 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            <span>Generate Kode</span>
            <span className="text-xl">🚀</span>
          </button>
        </div>

        {/* Generated Code */}
        {generatedCode && (
          <div className="rounded-xl bg-foreground/5 p-6 border border-foreground/10">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-lg font-semibold">Kode Yang Dihasilkan</h2>
              <button
                onClick={() => navigator.clipboard.writeText(generatedCode)}
                className="px-3 py-1 text-sm rounded-lg border border-foreground/10 hover:bg-foreground/5 transition-colors"
              >
                Copy Code
              </button>
            </div>
            <pre className="bg-black/50 p-4 rounded-lg overflow-x-auto">
              <code>{generatedCode}</code>
            </pre>
          </div>
        )}
      </main>
    </div>
  );
}